@sghss_HostAddress = http://localhost:3000

### REGISTER
POST {{sghss_HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
   "email": "teste@gmail.com",
   "password": "teste"
}


### LOGIN
POST {{sghss_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
   "email": "teste@gmail.com",
   "password": "teste"
}

### USERS
POST {{sghss_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
   "email": "teste1@gmail.com",
   "password": "teste",
   "name": "teste da silva",
   "role": "PATIENT",
   "cpf": "45885434824"
}