@sghss_HostAddress = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlNUBnbWFpbC5jb20iLCJzdWIiOjQsInJvbGUiOiJQQVRJRU5UIiwiaWF0IjoxNzQ0MTYyODYzLCJleHAiOjE3NDQxNjY0NjN9.dAQKXO0n6flFgB6rcm6p3ynp9m3sgPvkWSOIgkipMPw

### REGISTER
POST {{sghss_HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
   "email": "teste5@gmail.com",
   "password": "teste"
}


### LOGIN
POST {{sghss_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
   "email": "teste1@gmail.com",
   "password": "teste"
}

### USERS - CREATE
POST {{sghss_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
   "email": "teste1@gmail.com",
   "password": "teste",
   "name": "teste da silva",
   "role": "PATIENT",
   "cpf": "45885434824"
}

### USERS - GET ALL
GET {{sghss_HostAddress}}/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

### USERS - GET ONE
GET {{sghss_HostAddress}}/users/1
Accept: application/json
Content-Type: application/json

### USERS - UPDATE
PATCH  {{sghss_HostAddress}}/users/1
Accept: application/json
Content-Type: application/json

{
   "name": "teste da silva santos"
}

### USERS - DELETE
DELETE {{sghss_HostAddress}}/users/1
Accept: application/json
Content-Type: application/json


### PATIENTS - CREATE
POST {{sghss_HostAddress}}/patients
Accept: application/json
Content-Type: application/json