@sghss_HostAddress = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhZmFlbGFfbW9yZW5vQGhvdG1haWwuY29tIiwic3ViIjoxOCwicm9sZSI6IkFUVEVOREFOVCIsImlhdCI6MTc0NTQyNDY2NCwiZXhwIjoxNzQ1NDI4MjY0fQ.c23u5dXGDDeOLovwz0VPeme4JNjgTEkH6Ov-K9_L0mY

### REGISTER
POST {{sghss_HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
   "email": "teste5@gmail.com",
   "password": "teste"
}


### LOGIN
POST {{sghss_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
   "email": "rafaela_moreno@hotmail.com",
   "password": "12345"
}

### USERS - CREATE
POST {{sghss_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
   "email": "teste1@gmail.com",
   "password": "teste",
   "name": "teste da silva",
   "role": "PATIENT",
   "cpf": "45885434824"
}

### USERS - GET ALL
GET {{sghss_HostAddress}}/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

### USERS - GET ONE
GET {{sghss_HostAddress}}/users/7
Accept: application/json
Content-Type: application/json

### USERS - UPDATE
PATCH  {{sghss_HostAddress}}/users/1
Accept: application/json
Content-Type: application/json

{
   "name": "teste da silva santos"
}

### USERS - DELETE
DELETE {{sghss_HostAddress}}/users/9
Accept: application/json
Content-Type: application/json


### PATIENTS - CREATE
POST {{sghss_HostAddress}}/patients
Accept: application/json
Content-Type: application/json
# Authorization: Bearer {{ token }}

{
   "email": "mateus_leonardo19976@hotmail.com",
   "password": "12345",
   "name": "Mateus Leonardo dos Santos Sensão",
   "cpf": "49061545064",
   "bloodType": "O+",
}

### PATIENTS - GET ALL
GET {{sghss_HostAddress}}/patients
Accept: application/json
Content-Type: application/json

### PATIENTS - GET ONE
GET {{sghss_HostAddress}}/patients/1
Accept: application/json
Content-Type: application/json

### PATIENTS - UPDATE
PATCH  {{sghss_HostAddress}}/patients/13
Accept: application/json
Content-Type: application/json

{
   "allergies": "Dipirona"
}

### PATIENTS - DELETE
DELETE {{sghss_HostAddress}}/patients/9
Accept: application/json
Content-Type: application/json


### DOCTORS - CREATE
POST {{sghss_HostAddress}}/doctors
Accept: application/json
Content-Type: application/json
# Authorization: Bearer {{ token }}

{
   "email": "mateus_leonardo19974@hotmail.com",
   "password": "12345",
   "name": "Mateus Leonardo doutor",
   "cpf": "98742140072",
   "crm": "1234513",
   "specialty": "Cirurgiao"

}

### DOCTORS - GET ALL
GET {{sghss_HostAddress}}/doctors
Accept: application/json
Content-Type: application/json

### DOCTORS - GET ONE
GET {{sghss_HostAddress}}/doctors/
Accept: application/json
Content-Type: application/json

### DOCTORS - UPDATE
PATCH  {{sghss_HostAddress}}/doctors/13
Accept: application/json
Content-Type: application/json

{
   "allergies": "Dipirona"
}

### DOCTORS - DELETE
DELETE {{sghss_HostAddress}}/doctors/2
Accept: application/json
Content-Type: application/json


### ATTENDANTS - CREATE
POST {{sghss_HostAddress}}/attendants
Accept: application/json
Content-Type: application/json
# Authorization: Bearer {{ token }}

{
   "email": "rafaela_moreno@hotmail.com",
   "password": "12345",
   "name": "Rafaela Moreno",
   "cpf": "75068566039",
   "accessCode": "123456",
   "role": "ATTENDANT"
}

### ATTENDANTS - GET ALL
GET {{sghss_HostAddress}}/attendants
Accept: application/json
Content-Type: application/json

### ATTENDANTS - GET ONE
GET {{sghss_HostAddress}}/attendants/1
Accept: application/json
Content-Type: application/json

### ATTENDANTS - UPDATE
PATCH  {{sghss_HostAddress}}/attendants/13
Accept: application/json
Content-Type: application/json

{
   "accessCode": "12"
}

### ATTENDANTS - DELETE
DELETE {{sghss_HostAddress}}/attendants/2
Accept: application/json
Content-Type: application/json


### APPOINTMENTS - CREATE
POST {{sghss_HostAddress}}/appointments
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

{
   "doctorId": 1,
   "attendantId": 1,
   "patientId": 14,
   "date": "2025-05-05T10:20:00Z",
   "status": "PENDING",
   "duration": 30
}

### APPOINTMENTS - GET ALL
GET {{sghss_HostAddress}}/appointments
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

### APPOINTMENTS - GET ONE
GET {{sghss_HostAddress}}/appointments/1
Accept: application/json
Content-Type: application/json

### APPOINTMENTS - UPDATE
PATCH  {{sghss_HostAddress}}/appointments/13
Accept: application/json
Content-Type: application/json

{
   "allergies": "Dipirona"
}

### APPOINTMENTS - DELETE
DELETE {{sghss_HostAddress}}/appointments/2
Accept: application/json
Content-Type: application/json